Fix keystone test 'test_service_list'
'test_service_list' failed with
"E AttributeError: 'module' object has no attribute 'ServicesSteps'
 stepler/keystone/fixtures/services.py:41: AttributeError"
because of incorrect class name in the method's call.

Change-Id: If2ac2d8263a2a9f2b371c0f22c9b0d2c34056a05